import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation type for better type safety
type TranslationKeys = {
  [key: string]: string;
};

const translations = {
  en: {
    // Welcome & Auth
    'welcome.title': 'FadiFit',
    'welcome.subtitle': 'Transform your body with AI-powered fitness and nutrition plans tailored just for you',
    'welcome.createAccount': 'Create Account',
    'welcome.signIn': 'Sign In',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInSubtitle': 'Sign in to continue your journey',
    'auth.createAccountTitle': 'Create Account',
    'auth.createAccountSubtitle': 'Start your fitness transformation',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Name',
    'auth.forgotPassword': 'Forgot password?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.createOne': 'Create one',
    'auth.signInButton': 'Sign In',
    'auth.createAccountButton': 'Create Account',

    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.plan': 'Plan',
    'nav.progress': 'Progress',
    'nav.messages': 'Messages',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',

    // Dashboard
    'dashboard.goodMorning': 'Good morning',
    'dashboard.goodAfternoon': 'Good afternoon',
    'dashboard.goodEvening': 'Good evening',
    'dashboard.weeklyProgress': 'weekly progress',
    'dashboard.todayWorkout': "Today's Workout",
    'dashboard.nutrition': 'Nutrition',
    'dashboard.waterIntake': 'Water Intake',
    'dashboard.startWorkout': 'Start Workout',
    'dashboard.viewAll': 'View All',
    'dashboard.calories': 'Calories',
    'dashboard.eaten': 'Eaten',
    'dashboard.remaining': 'Remaining',

    // Workout
    'workout.exercises': 'exercises',
    'workout.minutes': 'min',
    'workout.sets': 'sets',
    'workout.reps': 'reps',
    'workout.startWorkout': 'Start Workout',
    'workout.doAgain': 'Do Again',
    'workout.exercise': 'Exercise',
    'workout.completed': 'Completed',
    'workout.currentSet': 'Current Set',
    'workout.target': 'Target',
    'workout.weight': 'Weight',
    'workout.bodyweight': 'Bodyweight',
    'workout.weighted': 'Weighted',
    'workout.machine': 'Machine',
    'workout.suggested': 'Suggested',
    'workout.logYourSets': 'Log Your Sets',
    'workout.completeSet': 'Complete Set',
    'workout.dropset': 'Dropset',
    'workout.addDropset': 'Add Dropset',
    'workout.setsCompleted': 'Sets Completed',
    'workout.previous': 'Previous',
    'workout.next': 'Next',
    'workout.finish': 'Finish',
    'workout.completeWorkout': 'Complete Workout',
    'workout.nextExercise': 'Next Exercise',
    'workout.restTime': 'Rest Time',
    'workout.skipRest': 'Skip Rest',
    'workout.getReady': 'Get ready for the next set',

    // Settings
    'settings.title': 'Settings',
    'settings.personalInfo': 'Personal Info',
    'settings.personalInfoSubtitle': 'Manage your profile details',
    'settings.goalsPreferences': 'Goals & Preferences',
    'settings.goalsPreferencesSubtitle': 'Fitness goals and preferences',
    'settings.notifications': 'Notifications',
    'settings.notificationsSubtitle': 'Control app notifications',
    'settings.subscription': 'Subscription',
    'settings.subscriptionSubtitle': 'Manage your plan and billing',
    'settings.language': 'Language',
    'settings.languageSubtitle': 'Change app language',
    'settings.about': 'About FadiFit',
    'settings.version': 'Version',
    'settings.build': 'Build',

    // Personal Info
    'personalInfo.title': 'Personal Info',
    'personalInfo.basicInfo': 'Basic Information',
    'personalInfo.physicalStats': 'Physical Stats',
    'personalInfo.fullName': 'Full Name',
    'personalInfo.email': 'Email',
    'personalInfo.phone': 'Phone Number (Optional)',
    'personalInfo.gender': 'Gender',
    'personalInfo.dateOfBirth': 'Date of Birth',
    'personalInfo.height': 'Height (cm)',
    'personalInfo.weight': 'Weight (kg)',
    'personalInfo.male': 'Male',
    'personalInfo.female': 'Female',
    'personalInfo.other': 'Other',
    'personalInfo.saveChanges': 'Save Changes',

    // Goals & Preferences
    'goals.title': 'Goals & Preferences',
    'goals.fitnessGoal': 'Fitness Goal',
    'goals.loseFat': 'Lose Fat',
    'goals.gainMuscle': 'Gain Muscle',
    'goals.maintain': 'Maintain',
    'goals.recomp': 'Recomposition',
    'goals.activityLevel': 'Activity Level',
    'goals.sedentary': 'Sedentary',
    'goals.sedentaryDesc': 'Little to no exercise',
    'goals.light': 'Light',
    'goals.lightDesc': '1-3 days per week',
    'goals.moderate': 'Moderate',
    'goals.moderateDesc': '3-5 days per week',
    'goals.active': 'Active',
    'goals.activeDesc': '6-7 days per week',
    'goals.veryActive': 'Very Active',
    'goals.veryActiveDesc': 'Intense daily training',
    'goals.trainingDays': 'Training Days Per Week',
    'goals.day': 'day',
    'goals.days': 'days',
    'goals.dietaryPreferences': 'Dietary Preferences',
    'goals.balanced': 'Balanced',
    'goals.highProtein': 'High Protein',
    'goals.vegetarian': 'Vegetarian',
    'goals.vegan': 'Vegan',
    'goals.glutenFree': 'Gluten-Free',
    'goals.dairyFree': 'Dairy-Free',
    'goals.waterTarget': 'Daily Water Target (glasses)',
    'goals.sleepTarget': 'Sleep Target (hours)',
    'goals.glasses': 'glasses',
    'goals.hours': 'hours',
    'goals.savePreferences': 'Save Preferences',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.workout': 'Workout Notifications',
    'notifications.workoutReminder': 'Workout Reminders',
    'notifications.workoutReminderDesc': 'Get notified before scheduled workouts',
    'notifications.missedWorkout': 'Missed Workout Alerts',
    'notifications.missedWorkoutDesc': 'Alerts when you miss a workout',
    'notifications.restDay': 'Rest Day Reminders',
    'notifications.restDayDesc': 'Remind you to take rest days',
    'notifications.nutrition': 'Nutrition Notifications',
    'notifications.mealReminder': 'Meal Reminders',
    'notifications.mealReminderDesc': 'Get notified for meal times',
    'notifications.calorieTracking': 'Calorie Tracking',
    'notifications.calorieTrackingDesc': 'Daily calorie goal reminders',
    'notifications.water': 'Water Reminders',
    'notifications.waterDesc': 'Stay hydrated throughout the day',
    'notifications.waterFrequency': 'Reminder Frequency',
    'notifications.every30min': 'Every 30 minutes',
    'notifications.everyHour': 'Every hour',
    'notifications.every90min': 'Every 90 minutes',
    'notifications.every2hours': 'Every 2 hours',
    'notifications.general': 'General Notifications',
    'notifications.appUpdates': 'App Updates',
    'notifications.appUpdatesDesc': 'New features and improvements',
    'notifications.coachMessages': 'Coach Messages',
    'notifications.coachMessagesDesc': 'Messages from your coach',
    'notifications.achievements': 'Achievements',
    'notifications.achievementsDesc': 'Celebrate your milestones',
    'notifications.save': 'Save Notification Settings',

    // Subscription
    'subscription.title': 'Subscription',
    'subscription.currentPlan': 'Current Plan',
    'subscription.premium': 'Premium',
    'subscription.active': 'Active',
    'subscription.perMonth': '/month',
    'subscription.availablePlans': 'Available Plans',
    'subscription.recommended': 'RECOMMENDED',
    'subscription.selectPlan': 'Select Plan',
    'subscription.billing': 'Billing',
    'subscription.paymentMethod': 'Payment Method',
    'subscription.nextBilling': 'Next Billing Date',
    'subscription.renewal': 'Renewal',
    'subscription.autoRenew': 'Auto-renew ON',
    'subscription.manageBilling': 'Manage Billing',
    'subscription.billingHistory': 'Billing History',
    'subscription.paid': 'Paid',
    'subscription.cancel': 'Cancel Subscription',

    // Language Selection
    'language.selectLanguage': 'Select Language',
    'language.chooseLanguage': 'Choose your preferred language',
    'language.english': 'English',
    'language.arabic': 'العربية',
    'language.spanish': 'Español',
    'language.continue': 'Continue',

    // Profile
    'profile.title': 'Profile',
    'profile.logout': 'Logout',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.done': 'Done',
    'common.close': 'Close',
    'common.kg': 'kg',
    'common.cm': 'cm',
    'common.next': 'Next',
    'common.continue': 'Continue',
    'common.skip': 'Skip',
    'common.back': 'Back',
    'common.select': 'Select',

    // Onboarding
    'onboarding.basicInfo': 'Basic Info',
    'onboarding.bodyComposition': 'Body Composition',
    'onboarding.fitnessProfile': 'Fitness Profile',
    'onboarding.health': 'Health',
    'onboarding.nutrition': 'Nutrition',
    'onboarding.review': 'Review & Generate',
    'onboarding.gender': 'Gender',
    'onboarding.selectGender': 'Select gender',
    'onboarding.male': 'Male',
    'onboarding.female': 'Female',
    'onboarding.other': 'Other',
    'onboarding.dateOfBirth': 'Date of Birth',
    'onboarding.height': 'Height (cm)',
    'onboarding.weight': 'Weight (kg)',
    'onboarding.bodyFat': 'Body Fat %',
    'onboarding.bodyFatOptional': 'Body Fat % (Optional)',
    'onboarding.fitnessLevel': 'Fitness Level',
    'onboarding.beginner': 'Beginner',
    'onboarding.intermediate': 'Intermediate',
    'onboarding.advanced': 'Advanced',
    'onboarding.fitnessGoal': 'Fitness Goal',
    'onboarding.injuries': 'Any Injuries or Limitations?',
    'onboarding.noInjuries': 'No injuries',
    'onboarding.mealsPerDay': 'Meals Per Day',
    'onboarding.allergies': 'Food Allergies',
    'onboarding.noAllergies': 'No allergies',
    'onboarding.reviewProfile': 'Review Your Profile',
    'onboarding.letsGo': "Let's Go!",
    'onboarding.generatePlan': 'Generate My Plan',

    // Forgot Password
    'forgot.title': 'Reset Password',
    'forgot.subtitle': "Enter your email address and we'll send you a link to reset your password.",
    'forgot.sendLink': 'Send Reset Link',
    'forgot.checkEmail': 'Check your email',
    'forgot.emailSent': "We've sent a password reset link to",

    // Generating
    'generating.title': 'Creating Your Plan',
    'generating.analyzing': 'Analyzing your goals...',
    'generating.building': 'Building your workout plan...',
    'generating.calculating': 'Calculating your calories...',
    'generating.optimizing': 'Optimizing your nutrition...',
    'generating.personalizing': 'Personalizing your experience...',
    'generating.almostReady': 'Almost ready...',

    // Workout Complete
    'complete.title': 'Workout Complete!',
    'complete.greatJob': 'Great Job!',
    'complete.stats': 'Workout Stats',
    'complete.duration': 'Duration',
    'complete.exercisesCompleted': 'Exercises Completed',
    'complete.caloriesBurned': 'Calories Burned',
    'complete.backToDashboard': 'Back to Dashboard',
    'complete.shareProgress': 'Share Progress',

    // Plan
    'plan.title': 'Workout Plan',
    'plan.weeklyPlan': 'Your Weekly Plan',
    'plan.workoutsDesigned': 'workouts designed for your goals',
    'plan.workoutTips': 'Workout Tips',

    // Meal & Nutrition
    'meal.breakfast': 'Breakfast',
    'meal.lunch': 'Lunch',
    'meal.dinner': 'Dinner',
    'meal.snacks': 'Snacks',
    'meal.protein': 'Protein',
    'meal.carbs': 'Carbs',
    'meal.fats': 'Fats',
    'meal.foods': 'Foods',
    'meal.markEaten': 'Mark as Eaten',

    // Progress & Add Progress
    'progress.title': 'Progress',
    'progress.weight': 'Weight',
    'progress.measurements': 'Measurements',
    'progress.photos': 'Photos',
    'progress.strength': 'Strength',
    'progress.current': 'Current',
    'progress.start': 'Start',
    'progress.change': 'Change',
    'progress.lastWeeks': 'Last 4 Weeks',
    'progress.noData': 'No data recorded yet',
    'addProgress.title': 'Add Progress',
    'addProgress.takePhoto': 'Take Photo',
    'addProgress.addMeasurements': 'Add Measurements',
    'addProgress.chest': 'Chest',
    'addProgress.waist': 'Waist',
    'addProgress.hips': 'Hips',
    'addProgress.arms': 'Arms',
    'addProgress.thighs': 'Thighs',

    // Messages
    'messages.title': 'Messages',
    'messages.noMessages': 'No messages yet',
    'messages.startConversation': 'Your coach will send you updates here',

    // Sign Up
    'signup.title': 'Create Account',
    'signup.subtitle': 'Start your fitness transformation',
    'signup.passwordMismatch': 'Passwords do not match',
  },
  ar: {
    // Welcome & Auth
    'welcome.title': 'فادي فِت',
    'welcome.subtitle': 'حوّل جسمك مع خطط اللياقة والتغذية المدعومة بالذكاء الاصطناعي والمصممة خصيصاً لك',
    'welcome.createAccount': 'إنشاء حساب',
    'welcome.signIn': 'تسجيل الدخول',
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.signInSubtitle': 'سجل دخولك لمواصلة رحلتك',
    'auth.createAccountTitle': 'إنشاء حساب',
    'auth.createAccountSubtitle': 'ابدأ تحولك في اللياقة البدنية',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.name': 'الاسم',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.dontHaveAccount': 'ليس لديك حساب؟',
    'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'auth.createOne': 'أنشئ واحداً',
    'auth.signInButton': 'تسجيل الدخول',
    'auth.createAccountButton': 'إنشاء حساب',

    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.plan': 'الخطة',
    'nav.progress': 'التقدم',
    'nav.messages': 'الرسائل',
    'nav.profile': 'الملف الشخصي',
    'nav.settings': 'الإعدادات',

    // Dashboard
    'dashboard.goodMorning': 'صباح الخير',
    'dashboard.goodAfternoon': 'مساء الخير',
    'dashboard.goodEvening': 'مساء الخير',
    'dashboard.weeklyProgress': 'التقدم الأسبوعي',
    'dashboard.todayWorkout': 'تمرين اليوم',
    'dashboard.nutrition': 'التغذية',
    'dashboard.waterIntake': 'شرب الماء',
    'dashboard.startWorkout': 'بدء التمرين',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.calories': 'السعرات الحرارية',
    'dashboard.eaten': 'المستهلك',
    'dashboard.remaining': 'المتبقي',

    // Workout
    'workout.exercises': 'تمارين',
    'workout.minutes': 'دقيقة',
    'workout.sets': 'مجموعات',
    'workout.reps': 'تكرارات',
    'workout.startWorkout': 'بدء التمرين',
    'workout.doAgain': 'إعادة التمرين',
    'workout.exercise': 'التمرين',
    'workout.completed': 'مكتمل',
    'workout.currentSet': 'المجموعة الحالية',
    'workout.target': 'الهدف',
    'workout.weight': 'الوزن',
    'workout.bodyweight': 'وزن الجسم',
    'workout.weighted': 'بوزن إضافي',
    'workout.machine': 'آلة',
    'workout.suggested': 'مقترح',
    'workout.logYourSets': 'سجل مجموعاتك',
    'workout.completeSet': 'إكمال المجموعة',
    'workout.dropset': 'دروبسيت',
    'workout.addDropset': 'إضافة دروبسيت',
    'workout.setsCompleted': 'المجموعات المكتملة',
    'workout.previous': 'السابق',
    'workout.next': 'التالي',
    'workout.finish': 'إنهاء',
    'workout.completeWorkout': 'إكمال التمرين',
    'workout.nextExercise': 'التمرين التالي',
    'workout.restTime': 'وقت الراحة',
    'workout.skipRest': 'تخطي الراحة',
    'workout.getReady': 'استعد للمجموعة التالية',

    // Settings
    'settings.title': 'الإعدادات',
    'settings.personalInfo': 'المعلومات الشخصية',
    'settings.personalInfoSubtitle': 'إدارة تفاصيل ملفك الشخصي',
    'settings.goalsPreferences': 'الأهداف والتفضيلات',
    'settings.goalsPreferencesSubtitle': 'أهداف اللياقة والتفضيلات',
    'settings.notifications': 'الإشعارات',
    'settings.notificationsSubtitle': 'التحكم في إشعارات التطبيق',
    'settings.subscription': 'الاشتراك',
    'settings.subscriptionSubtitle': 'إدارة خطتك والفواتير',
    'settings.language': 'اللغة',
    'settings.languageSubtitle': 'تغيير لغة التطبيق',
    'settings.about': 'حول فادي فِت',
    'settings.version': 'الإصدار',
    'settings.build': 'البناء',

    // Personal Info
    'personalInfo.title': 'المعلومات الشخصية',
    'personalInfo.basicInfo': 'المعلومات الأساسية',
    'personalInfo.physicalStats': 'الإحصائيات الجسدية',
    'personalInfo.fullName': 'الاسم الكامل',
    'personalInfo.email': 'البريد الإلكتروني',
    'personalInfo.phone': 'رقم الهاتف (اختياري)',
    'personalInfo.gender': 'الجنس',
    'personalInfo.dateOfBirth': 'تاريخ الميلاد',
    'personalInfo.height': 'الطول (سم)',
    'personalInfo.weight': 'الوزن (كجم)',
    'personalInfo.male': 'ذكر',
    'personalInfo.female': 'أنثى',
    'personalInfo.other': 'آخر',
    'personalInfo.saveChanges': 'حفظ التغييرات',

    // Goals & Preferences
    'goals.title': 'الأهداف والتفضيلات',
    'goals.fitnessGoal': 'هدف اللياقة',
    'goals.loseFat': 'خسارة الدهون',
    'goals.gainMuscle': 'بناء العضلات',
    'goals.maintain': 'المحافظة',
    'goals.recomp': 'إعادة التكوين',
    'goals.activityLevel': 'مستوى النشاط',
    'goals.sedentary': 'قليل الحركة',
    'goals.sedentaryDesc': 'لا توجد تمارين أو قليلة جداً',
    'goals.light': 'خفيف',
    'goals.lightDesc': '1-3 أيام في الأسبوع',
    'goals.moderate': 'متوسط',
    'goals.moderateDesc': '3-5 أيام في الأسبوع',
    'goals.active': 'نشط',
    'goals.activeDesc': '6-7 أيام في الأسبوع',
    'goals.veryActive': 'نشط جداً',
    'goals.veryActiveDesc': 'تدريب مكثف يومياً',
    'goals.trainingDays': 'أيام التدريب في الأسبوع',
    'goals.day': 'يوم',
    'goals.days': 'أيام',
    'goals.dietaryPreferences': 'التفضيلات الغذائية',
    'goals.balanced': 'متوازن',
    'goals.highProtein': 'عالي البروتين',
    'goals.vegetarian': 'نباتي',
    'goals.vegan': 'نباتي صرف',
    'goals.glutenFree': 'خالي من الجلوتين',
    'goals.dairyFree': 'خالي من الألبان',
    'goals.waterTarget': 'هدف الماء اليومي (أكواب)',
    'goals.sleepTarget': 'هدف النوم (ساعات)',
    'goals.glasses': 'أكواب',
    'goals.hours': 'ساعات',
    'goals.savePreferences': 'حفظ التفضيلات',

    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.workout': 'إشعارات التمارين',
    'notifications.workoutReminder': 'تذكير بالتمارين',
    'notifications.workoutReminderDesc': 'احصل على إشعار قبل التمارين المجدولة',
    'notifications.missedWorkout': 'تنبيهات التمارين الفائتة',
    'notifications.missedWorkoutDesc': 'تنبيهات عند تفويت تمرين',
    'notifications.restDay': 'تذكير بأيام الراحة',
    'notifications.restDayDesc': 'تذكيرك بأخذ أيام راحة',
    'notifications.nutrition': 'إشعارات التغذية',
    'notifications.mealReminder': 'تذكير بالوجبات',
    'notifications.mealReminderDesc': 'احصل على إشعار لأوقات الوجبات',
    'notifications.calorieTracking': 'تتبع السعرات',
    'notifications.calorieTrackingDesc': 'تذكير بأهداف السعرات اليومية',
    'notifications.water': 'تذكير بالماء',
    'notifications.waterDesc': 'ابقَ رطباً طوال اليوم',
    'notifications.waterFrequency': 'تكرار التذكير',
    'notifications.every30min': 'كل 30 دقيقة',
    'notifications.everyHour': 'كل ساعة',
    'notifications.every90min': 'كل 90 دقيقة',
    'notifications.every2hours': 'كل ساعتين',
    'notifications.general': 'الإشعارات العامة',
    'notifications.appUpdates': 'تحديثات التطبيق',
    'notifications.appUpdatesDesc': 'ميزات وتحسينات جديدة',
    'notifications.coachMessages': 'رسائل المدرب',
    'notifications.coachMessagesDesc': 'رسائل من مدربك',
    'notifications.achievements': 'الإنجازات',
    'notifications.achievementsDesc': 'احتفل بإنجازاتك',
    'notifications.save': 'حفظ إعدادات الإشعارات',

    // Subscription
    'subscription.title': 'الاشتراك',
    'subscription.currentPlan': 'الخطة الحالية',
    'subscription.premium': 'بريميوم',
    'subscription.active': 'نشط',
    'subscription.perMonth': '/شهر',
    'subscription.availablePlans': 'الخطط المتاحة',
    'subscription.recommended': 'موصى به',
    'subscription.selectPlan': 'اختر الخطة',
    'subscription.billing': 'الفواتير',
    'subscription.paymentMethod': 'طريقة الدفع',
    'subscription.nextBilling': 'تاريخ الفاتورة التالية',
    'subscription.renewal': 'التجديد',
    'subscription.autoRenew': 'التجديد التلقائي مفعّل',
    'subscription.manageBilling': 'إدارة الفواتير',
    'subscription.billingHistory': 'سجل الفواتير',
    'subscription.paid': 'مدفوع',
    'subscription.cancel': 'إلغاء الاشتراك',

    // Language Selection
    'language.selectLanguage': 'اختر اللغة',
    'language.chooseLanguage': 'اختر لغتك المفضلة',
    'language.english': 'English',
    'language.arabic': 'العربية',
    'language.spanish': 'Español',
    'language.continue': 'متابعة',

    // Profile
    'profile.title': 'الملف الشخصي',
    'profile.logout': 'تسجيل الخروج',

    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.done': 'تم',
    'common.close': 'إغلاق',
    'common.kg': 'كجم',
    'common.cm': 'سم',
    'common.next': 'التالي',
    'common.continue': 'متابعة',
    'common.skip': 'تخطي',
    'common.back': 'رجوع',
    'common.select': 'اختر',

    // Onboarding
    'onboarding.basicInfo': 'المعلومات الأساسية',
    'onboarding.bodyComposition': 'تكوين الجسم',
    'onboarding.fitnessProfile': 'ملف اللياقة',
    'onboarding.health': 'الصحة',
    'onboarding.nutrition': 'التغذية',
    'onboarding.review': 'المراجعة والإنشاء',
    'onboarding.gender': 'الجنس',
    'onboarding.selectGender': 'اختر الجنس',
    'onboarding.male': 'ذكر',
    'onboarding.female': 'أنثى',
    'onboarding.other': 'آخر',
    'onboarding.dateOfBirth': 'تاريخ الميلاد',
    'onboarding.height': 'الطول (سم)',
    'onboarding.weight': 'الوزن (كجم)',
    'onboarding.bodyFat': 'نسبة الدهون %',
    'onboarding.bodyFatOptional': 'نسبة الدهون % (اختياري)',
    'onboarding.fitnessLevel': 'مستوى اللياقة',
    'onboarding.beginner': 'مبتدئ',
    'onboarding.intermediate': 'متوسط',
    'onboarding.advanced': 'متقدم',
    'onboarding.fitnessGoal': 'هدف اللياقة',
    'onboarding.injuries': 'هل لديك إصابات أو قيود؟',
    'onboarding.noInjuries': 'لا توجد إصابات',
    'onboarding.mealsPerDay': 'الوجبات في اليوم',
    'onboarding.allergies': 'حساسية الطعام',
    'onboarding.noAllergies': 'لا توجد حساسية',
    'onboarding.reviewProfile': 'راجع ملفك الشخصي',
    'onboarding.letsGo': 'لنبدأ!',
    'onboarding.generatePlan': 'إنشاء خطتي',

    // Forgot Password
    'forgot.title': 'إعادة تعيين كلمة المرور',
    'forgot.subtitle': 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.',
    'forgot.sendLink': 'إرسال رابط إعادة التعيين',
    'forgot.checkEmail': 'تحقق من بريدك الإلكتروني',
    'forgot.emailSent': 'لقد أرسلنا رابط إعادة تعيين كلمة المرور إلى',

    // Generating
    'generating.title': 'إنشاء خطتك',
    'generating.analyzing': 'تحليل أهدافك...',
    'generating.building': 'بناء خطة التمرين...',
    'generating.calculating': 'حساب السعرات الحرارية...',
    'generating.optimizing': 'تحسين التغذية...',
    'generating.personalizing': 'تخصيص تجربتك...',
    'generating.almostReady': 'تقريباً جاهز...',

    // Workout Complete
    'complete.title': 'اكتمل التمرين!',
    'complete.greatJob': 'عمل رائع!',
    'complete.stats': 'إحصائيات التمرين',
    'complete.duration': 'المدة',
    'complete.exercisesCompleted': 'التمارين المكتملة',
    'complete.caloriesBurned': 'السعرات المحروقة',
    'complete.backToDashboard': 'العودة للوحة التحكم',
    'complete.shareProgress': 'مشاركة التقدم',

    // Plan
    'plan.title': 'خطة التمرين',
    'plan.weeklyPlan': 'خطتك الأسبوعية',
    'plan.workoutsDesigned': 'تمارين مصممة لأهدافك',
    'plan.workoutTips': 'نصائح التمرين',

    // Meal & Nutrition
    'meal.breakfast': 'الإفطار',
    'meal.lunch': 'الغداء',
    'meal.dinner': 'العشاء',
    'meal.snacks': 'الوجبات الخفيفة',
    'meal.protein': 'البروتين',
    'meal.carbs': 'الكربوهيدرات',
    'meal.fats': 'الدهون',
    'meal.foods': 'الأطعمة',
    'meal.markEaten': 'تحديد كمستهلك',

    // Progress & Add Progress
    'progress.title': 'التقدم',
    'progress.weight': 'الوزن',
    'progress.measurements': 'القياسات',
    'progress.photos': 'الصور',
    'progress.strength': 'القوة',
    'progress.current': 'الحالي',
    'progress.start': 'البداية',
    'progress.change': 'التغيير',
    'progress.lastWeeks': 'آخر 4 أسابيع',
    'progress.noData': 'لم يتم تسجيل بيانات بعد',
    'addProgress.title': 'إضافة تقدم',
    'addProgress.takePhoto': 'التقاط صورة',
    'addProgress.addMeasurements': 'إضافة قياسات',
    'addProgress.chest': 'الصدر',
    'addProgress.waist': 'الخصر',
    'addProgress.hips': 'الأرداف',
    'addProgress.arms': 'الذراعين',
    'addProgress.thighs': 'الفخذين',

    // Messages
    'messages.title': 'الرسائل',
    'messages.noMessages': 'لا توجد رسائل بعد',
    'messages.startConversation': 'سيرسل لك مدربك التحديثات هنا',

    // Sign Up
    'signup.title': 'إنشاء حساب',
    'signup.subtitle': 'ابدأ تحولك في اللياقة البدنية',
    'signup.passwordMismatch': 'كلمات المرور غير متطابقة',
  },
  es: {
    // Welcome & Auth
    'welcome.title': 'FadiFit',
    'welcome.subtitle': 'Transforma tu cuerpo con planes de fitness y nutrición impulsados por IA diseñados solo para ti',
    'welcome.createAccount': 'Crear Cuenta',
    'welcome.signIn': 'Iniciar Sesión',
    'auth.welcomeBack': 'Bienvenido de nuevo',
    'auth.signInSubtitle': 'Inicia sesión para continuar tu viaje',
    'auth.createAccountTitle': 'Crear Cuenta',
    'auth.createAccountSubtitle': 'Comienza tu transformación fitness',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.name': 'Nombre',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.dontHaveAccount': '¿No tienes una cuenta?',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.createOne': 'Crea una',
    'auth.signInButton': 'Iniciar Sesión',
    'auth.createAccountButton': 'Crear Cuenta',

    // Navigation
    'nav.dashboard': 'Panel',
    'nav.plan': 'Plan',
    'nav.progress': 'Progreso',
    'nav.messages': 'Mensajes',
    'nav.profile': 'Perfil',
    'nav.settings': 'Ajustes',

    // Dashboard
    'dashboard.goodMorning': 'Buenos días',
    'dashboard.goodAfternoon': 'Buenas tardes',
    'dashboard.goodEvening': 'Buenas noches',
    'dashboard.weeklyProgress': 'progreso semanal',
    'dashboard.todayWorkout': 'Entrenamiento de Hoy',
    'dashboard.nutrition': 'Nutrición',
    'dashboard.waterIntake': 'Consumo de Agua',
    'dashboard.startWorkout': 'Comenzar Entrenamiento',
    'dashboard.viewAll': 'Ver Todo',
    'dashboard.calories': 'Calorías',
    'dashboard.eaten': 'Consumidas',
    'dashboard.remaining': 'Restantes',

    // Workout
    'workout.exercises': 'ejercicios',
    'workout.minutes': 'min',
    'workout.sets': 'series',
    'workout.reps': 'reps',
    'workout.startWorkout': 'Comenzar Entrenamiento',
    'workout.doAgain': 'Repetir',
    'workout.exercise': 'Ejercicio',
    'workout.completed': 'Completado',
    'workout.currentSet': 'Serie Actual',
    'workout.target': 'Objetivo',
    'workout.weight': 'Peso',
    'workout.bodyweight': 'Peso Corporal',
    'workout.weighted': 'Con Peso',
    'workout.machine': 'Máquina',
    'workout.suggested': 'Sugerido',
    'workout.logYourSets': 'Registra tus Series',
    'workout.completeSet': 'Completar Serie',
    'workout.dropset': 'Dropset',
    'workout.addDropset': 'Añadir Dropset',
    'workout.setsCompleted': 'Series Completadas',
    'workout.previous': 'Anterior',
    'workout.next': 'Siguiente',
    'workout.finish': 'Finalizar',
    'workout.completeWorkout': 'Completar Entrenamiento',
    'workout.nextExercise': 'Siguiente Ejercicio',
    'workout.restTime': 'Tiempo de Descanso',
    'workout.skipRest': 'Saltar Descanso',
    'workout.getReady': 'Prepárate para la siguiente serie',

    // Settings
    'settings.title': 'Ajustes',
    'settings.personalInfo': 'Información Personal',
    'settings.personalInfoSubtitle': 'Gestiona los detalles de tu perfil',
    'settings.goalsPreferences': 'Objetivos y Preferencias',
    'settings.goalsPreferencesSubtitle': 'Objetivos fitness y preferencias',
    'settings.notifications': 'Notificaciones',
    'settings.notificationsSubtitle': 'Controla las notificaciones de la app',
    'settings.subscription': 'Suscripción',
    'settings.subscriptionSubtitle': 'Gestiona tu plan y facturación',
    'settings.language': 'Idioma',
    'settings.languageSubtitle': 'Cambiar idioma de la app',
    'settings.about': 'Acerca de FadiFit',
    'settings.version': 'Versión',
    'settings.build': 'Build',

    // Personal Info
    'personalInfo.title': 'Información Personal',
    'personalInfo.basicInfo': 'Información Básica',
    'personalInfo.physicalStats': 'Estadísticas Físicas',
    'personalInfo.fullName': 'Nombre Completo',
    'personalInfo.email': 'Correo Electrónico',
    'personalInfo.phone': 'Número de Teléfono (Opcional)',
    'personalInfo.gender': 'Género',
    'personalInfo.dateOfBirth': 'Fecha de Nacimiento',
    'personalInfo.height': 'Altura (cm)',
    'personalInfo.weight': 'Peso (kg)',
    'personalInfo.male': 'Masculino',
    'personalInfo.female': 'Femenino',
    'personalInfo.other': 'Otro',
    'personalInfo.saveChanges': 'Guardar Cambios',

    // Goals & Preferences
    'goals.title': 'Objetivos y Preferencias',
    'goals.fitnessGoal': 'Objetivo Fitness',
    'goals.loseFat': 'Perder Grasa',
    'goals.gainMuscle': 'Ganar Músculo',
    'goals.maintain': 'Mantener',
    'goals.recomp': 'Recomposición',
    'goals.activityLevel': 'Nivel de Actividad',
    'goals.sedentary': 'Sedentario',
    'goals.sedentaryDesc': 'Poco o ningún ejercicio',
    'goals.light': 'Ligero',
    'goals.lightDesc': '1-3 días por semana',
    'goals.moderate': 'Moderado',
    'goals.moderateDesc': '3-5 días por semana',
    'goals.active': 'Activo',
    'goals.activeDesc': '6-7 días por semana',
    'goals.veryActive': 'Muy Activo',
    'goals.veryActiveDesc': 'Entrenamiento intenso diario',
    'goals.trainingDays': 'Días de Entrenamiento por Semana',
    'goals.day': 'día',
    'goals.days': 'días',
    'goals.dietaryPreferences': 'Preferencias Dietéticas',
    'goals.balanced': 'Equilibrado',
    'goals.highProtein': 'Alto en Proteínas',
    'goals.vegetarian': 'Vegetariano',
    'goals.vegan': 'Vegano',
    'goals.glutenFree': 'Sin Gluten',
    'goals.dairyFree': 'Sin Lácteos',
    'goals.waterTarget': 'Objetivo Diario de Agua (vasos)',
    'goals.sleepTarget': 'Objetivo de Sueño (horas)',
    'goals.glasses': 'vasos',
    'goals.hours': 'horas',
    'goals.savePreferences': 'Guardar Preferencias',

    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.workout': 'Notificaciones de Entrenamiento',
    'notifications.workoutReminder': 'Recordatorios de Entrenamiento',
    'notifications.workoutReminderDesc': 'Recibe notificaciones antes de entrenamientos programados',
    'notifications.missedWorkout': 'Alertas de Entrenamiento Perdido',
    'notifications.missedWorkoutDesc': 'Alertas cuando pierdes un entrenamiento',
    'notifications.restDay': 'Recordatorios de Día de Descanso',
    'notifications.restDayDesc': 'Recordarte tomar días de descanso',
    'notifications.nutrition': 'Notificaciones de Nutrición',
    'notifications.mealReminder': 'Recordatorios de Comidas',
    'notifications.mealReminderDesc': 'Recibe notificaciones para horarios de comidas',
    'notifications.calorieTracking': 'Seguimiento de Calorías',
    'notifications.calorieTrackingDesc': 'Recordatorios de objetivo calórico diario',
    'notifications.water': 'Recordatorios de Agua',
    'notifications.waterDesc': 'Mantente hidratado durante el día',
    'notifications.waterFrequency': 'Frecuencia de Recordatorio',
    'notifications.every30min': 'Cada 30 minutos',
    'notifications.everyHour': 'Cada hora',
    'notifications.every90min': 'Cada 90 minutos',
    'notifications.every2hours': 'Cada 2 horas',
    'notifications.general': 'Notificaciones Generales',
    'notifications.appUpdates': 'Actualizaciones de la App',
    'notifications.appUpdatesDesc': 'Nuevas funciones y mejoras',
    'notifications.coachMessages': 'Mensajes del Coach',
    'notifications.coachMessagesDesc': 'Mensajes de tu entrenador',
    'notifications.achievements': 'Logros',
    'notifications.achievementsDesc': 'Celebra tus hitos',
    'notifications.save': 'Guardar Configuración de Notificaciones',

    // Subscription
    'subscription.title': 'Suscripción',
    'subscription.currentPlan': 'Plan Actual',
    'subscription.premium': 'Premium',
    'subscription.active': 'Activo',
    'subscription.perMonth': '/mes',
    'subscription.availablePlans': 'Planes Disponibles',
    'subscription.recommended': 'RECOMENDADO',
    'subscription.selectPlan': 'Seleccionar Plan',
    'subscription.billing': 'Facturación',
    'subscription.paymentMethod': 'Método de Pago',
    'subscription.nextBilling': 'Próxima Fecha de Facturación',
    'subscription.renewal': 'Renovación',
    'subscription.autoRenew': 'Auto-renovación ACTIVADA',
    'subscription.manageBilling': 'Gestionar Facturación',
    'subscription.billingHistory': 'Historial de Facturación',
    'subscription.paid': 'Pagado',
    'subscription.cancel': 'Cancelar Suscripción',

    // Language Selection
    'language.selectLanguage': 'Seleccionar Idioma',
    'language.chooseLanguage': 'Elige tu idioma preferido',
    'language.english': 'English',
    'language.arabic': 'العربية',
    'language.spanish': 'Español',
    'language.continue': 'Continuar',

    // Profile
    'profile.title': 'Perfil',
    'profile.logout': 'Cerrar Sesión',

    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.done': 'Hecho',
    'common.close': 'Cerrar',
    'common.kg': 'kg',
    'common.cm': 'cm',
    'common.next': 'Siguiente',
    'common.continue': 'Continuar',
    'common.skip': 'Saltar',
    'common.back': 'Atrás',
    'common.select': 'Seleccionar',

    // Onboarding
    'onboarding.basicInfo': 'Información Básica',
    'onboarding.bodyComposition': 'Composición Corporal',
    'onboarding.fitnessProfile': 'Perfil Fitness',
    'onboarding.health': 'Salud',
    'onboarding.nutrition': 'Nutrición',
    'onboarding.review': 'Revisar y Generar',
    'onboarding.gender': 'Género',
    'onboarding.selectGender': 'Seleccionar género',
    'onboarding.male': 'Masculino',
    'onboarding.female': 'Femenino',
    'onboarding.other': 'Otro',
    'onboarding.dateOfBirth': 'Fecha de Nacimiento',
    'onboarding.height': 'Altura (cm)',
    'onboarding.weight': 'Peso (kg)',
    'onboarding.bodyFat': 'Grasa Corporal %',
    'onboarding.bodyFatOptional': 'Grasa Corporal % (Opcional)',
    'onboarding.fitnessLevel': 'Nivel de Fitness',
    'onboarding.beginner': 'Principiante',
    'onboarding.intermediate': 'Intermedio',
    'onboarding.advanced': 'Avanzado',
    'onboarding.fitnessGoal': 'Objetivo Fitness',
    'onboarding.injuries': '¿Alguna lesión o limitación?',
    'onboarding.noInjuries': 'Sin lesiones',
    'onboarding.mealsPerDay': 'Comidas por Día',
    'onboarding.allergies': 'Alergias Alimentarias',
    'onboarding.noAllergies': 'Sin alergias',
    'onboarding.reviewProfile': 'Revisa tu Perfil',
    'onboarding.letsGo': '¡Vamos!',
    'onboarding.generatePlan': 'Generar Mi Plan',

    // Forgot Password
    'forgot.title': 'Restablecer Contraseña',
    'forgot.subtitle': 'Ingresa tu dirección de correo electrónico y te enviaremos un enlace para restablecer tu contraseña.',
    'forgot.sendLink': 'Enviar Enlace de Restablecimiento',
    'forgot.checkEmail': 'Revisa tu correo',
    'forgot.emailSent': 'Hemos enviado un enlace de restablecimiento de contraseña a',

    // Generating
    'generating.title': 'Creando tu Plan',
    'generating.analyzing': 'Analizando tus objetivos...',
    'generating.building': 'Construyendo tu plan de entrenamiento...',
    'generating.calculating': 'Calculando tus calorías...',
    'generating.optimizing': 'Optimizando tu nutrición...',
    'generating.personalizing': 'Personalizando tu experiencia...',
    'generating.almostReady': 'Casi listo...',

    // Workout Complete
    'complete.title': '¡Entrenamiento Completado!',
    'complete.greatJob': '¡Buen Trabajo!',
    'complete.stats': 'Estadísticas del Entrenamiento',
    'complete.duration': 'Duración',
    'complete.exercisesCompleted': 'Ejercicios Completados',
    'complete.caloriesBurned': 'Calorías Quemadas',
    'complete.backToDashboard': 'Volver al Panel',
    'complete.shareProgress': 'Compartir Progreso',

    // Plan
    'plan.title': 'Plan de Entrenamiento',
    'plan.weeklyPlan': 'Tu Plan Semanal',
    'plan.workoutsDesigned': 'entrenamientos diseñados para tus objetivos',
    'plan.workoutTips': 'Consejos de Entrenamiento',

    // Meal & Nutrition
    'meal.breakfast': 'Desayuno',
    'meal.lunch': 'Almuerzo',
    'meal.dinner': 'Cena',
    'meal.snacks': 'Refrigerios',
    'meal.protein': 'Proteína',
    'meal.carbs': 'Carbohidratos',
    'meal.fats': 'Grasas',
    'meal.foods': 'Alimentos',
    'meal.markEaten': 'Marcar como Consumido',

    // Progress & Add Progress
    'progress.title': 'Progreso',
    'progress.weight': 'Peso',
    'progress.measurements': 'Medidas',
    'progress.photos': 'Fotos',
    'progress.strength': 'Fuerza',
    'progress.current': 'Actual',
    'progress.start': 'Inicio',
    'progress.change': 'Cambio',
    'progress.lastWeeks': 'Últimas 4 Semanas',
    'progress.noData': 'No se han registrado datos aún',
    'addProgress.title': 'Añadir Progreso',
    'addProgress.takePhoto': 'Tomar Foto',
    'addProgress.addMeasurements': 'Añadir Medidas',
    'addProgress.chest': 'Pecho',
    'addProgress.waist': 'Cintura',
    'addProgress.hips': 'Caderas',
    'addProgress.arms': 'Brazos',
    'addProgress.thighs': 'Muslos',

    // Messages
    'messages.title': 'Mensajes',
    'messages.noMessages': 'No hay mensajes aún',
    'messages.startConversation': 'Tu entrenador te enviará actualizaciones aquí',

    // Sign Up
    'signup.title': 'Crear Cuenta',
    'signup.subtitle': 'Comienza tu transformación fitness',
    'signup.passwordMismatch': 'Las contraseñas no coinciden',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('fadifit-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('fadifit-language', lang);
    // Update document direction for RTL
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  // Set initial direction
  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
